[package]
name = "dll-export"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "1.0.107"
proc-macro2 = "1.0.50"
macro-impl = { path = "./macro-impl" }
