name: Lints and formatting
on: [push, pull_request]
jobs:
  clippy:
    name: cargo clippy
    runs-on: windows-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-09-20
          targets: x86_64-pc-windows-msvc
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      - run: cargo clippy --workspace --target x86_64-pc-windows-msvc
      - run: cargo clippy --workspace --target x86_64-pc-windows-msvc --no-default-features --features windows
      - run: cargo clippy --workspace --target x86_64-pc-windows-msvc --no-default-features --features docker
      - run: cargo fmt --check --all
